apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: site-ssplab
spec:
  project: default
  source:
    repoURL: https://github.com/InseeFrLab/site-ssplab.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: user-sitessplab
  syncPolicy:
    automated:
      selfHeal: true
