# Generated by Django 3.1.7 on 2021-03-17 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Explo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('date_debut', models.DateField(default=datetime.date.today)),
                ('date_fin', models.DateField(default=datetime.date.today)),
                ('image_titre', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
            ],
            options={
                'ordering': ['-date_fin'],
            },
        ),
    ]
