apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-ssplab
spec:
  selector:
    matchLabels:
      app: site-ssplab
  template:
    metadata:
      labels:
        app: site-ssplab
    spec:
      containers:
      - name: site-ssplab
        image: inseefrlab/site-ssplab:main
        volumeMounts:
        - mountPath: "/usr/share/data/"
          name: site-ssplab-pv
        imagePullPolicy: Always
        resources:
          limits:
            memory: "5Gi"
            cpu: "500m"
        env: 
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: django-secret
                key: key
      volumes:
      - name: site-ssplab-pv
        persistentVolumeClaim:
          claimName: site-ssplab-pvc
