apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  rules:
  - host: ssplab.lab.sspcloud.fr
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: myapp
            port: 
              number: 80
