# Generated by Django 3.1.7 on 2021-03-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210311_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
